123:
  notifications:
    sailing_hour: 7
    saling_duration: 2
    spot: marina_tel_aviv
  thresholds:
    wave: 1
    wind: 4
630924196:
  notifications:
    sailing_hour: 7
    saling_duration: 2
    spot: marina_tel_aviv
  thresholds:
    wave: 1.3
    wind: 5
